//Map Images
export const  Flag1 = require('../../assets/images/map/1.png')
export const  Flag2 = require('../../assets/images/map/2.png')
export const  Flag3 = require('../../assets/images/map/3.png')
export const  Flag4 = require('../../assets/images/map/4.png')
export const  Flag5 = require('../../assets/images/map/5.png')
export const  Flag6 = require('../../assets/images/map/6.png')
export const  Flag7 = require('../../assets/images/map/7.png')
export const  Flag8 = require('../../assets/images/map/8.png')
export const  Flag9 = require('../../assets/images/map/9.png')
export const  Flag10 = require('../../assets/images/map/10.png')