//Map Images
export const  Flag1 = require('../../assets/images/Africa/Africa-Algeria.png')
export const  Flag2 = require('../../assets/images/Africa/Africa-Angola.png')
export const  Flag3 = require('../../assets/images/Africa/Africa-Benin.png')
export const  Flag4 = require('../../assets/images/Africa/Africa-Botswana.png')
export const  Flag5 = require('../../assets/images/Africa/Africa-Burundi.png')
export const  Flag6 = require('../../assets/images/Africa/Africa-Cameroon.png')
export const  Flag7 = require('../../assets/images/Africa/Africa-Chad.png')
export const  Flag8 = require('../../assets/images/Africa/Africa-Comoros.png')
export const  Flag9 = require('../../assets/images/Africa/Africa-Djibouti.png')
export const  Flag10 = require('../../assets/images/Africa/Africa-Egypt.png')